version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile-prod
    command: gunicorn drm_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ../drm_backend/.env
    environment:
      - PROD=1

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: